namespace CustomerManagementApi.Models
{
    /// <summary>
    /// Represents a customer record stored by the application.
    /// </summary>
    public class Customer
    {
        /// <summary>
        /// Primary key. Value is generated by the data store when the entity is saved.
        /// </summary>
        public int Id { get; set; }

        /// <summary>
        /// Customer given name.
        /// </summary>
        public string? FirstName { get; set; }

        /// <summary>
        /// Customer family name.
        /// </summary>
        public string? LastName { get; set; }

        /// <summary>
        /// Contact email for the customer.
        /// </summary>
        public string? Email { get; set; }

        /// <summary>
        /// Timestamp when the customer record was created. Defaults to <see cref="DateTime.UtcNow"/>.
        /// </summary>
        public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
    }
}